#!/bin/bash

file=${1:-input.mp4}
rate=${2:-24}
method=${3:-optimizeplus}

# Convert the input video to still frames.
ffmpeg -i $file -r $rate gif_output%05d.png

# Convert the still frames to a GIF.
convert -dispose none -delay 2 -layers $method gif_output*.png "${file%.*}.gif"

# Clean up by removing the still frames.
rm gif_output*.png
